### ISSUE TITLE
How “ findTime” works ?

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [facebookincubator/LogDevice#108]
I guess it first finds a partition based on LogID and timestamp (partition are created by default accumulation of 15 minutes), then traverses KV in this column family, and then matches timestamp in value. 
If I adjust the time period / storage space of partition to a larger extent, will it affect the efficiency of findtime ?

**Comment by MohamedBassem** [comment]
@zhengxiaochuan-3 feel free to re-open this issue if you still have further questions.
