### ISSUE TITLE
Logdeviced crashes while zookeeper node creation

### ISSUE THREAD

**Issue by Krestol** [facebookincubator/LogDevice#115]
**Steps**:
1. remove folder logdevice in zookeeper (if exist)
2. empty local logdevice storage
3. run cluster

**Actual result**:
logdevice nodes crash after several seconds
empty logdevice folder is created in zookeeper

**Expectred result**:
loogdevice cluster run successfully

Error in logdevice log:
`I0926 14:34:05.642572    1245 [not-set] ZookeeperEpochStore.cpp:218] operator()() Root znode doesn't exist, creating it.
E0926 14:34:05.647154    1245 [not-set] ZookeeperClientBase.cpp:51] toStatus() Unknown / unexpected Zookeeper error code -114
E0926 14:34:05.647518    1245 [not-set] ZookeeperEpochStore.cpp:173] completionStatus() Got unexpected status code invalid acl from Zookeeper completion function for log 0
C0926 14:34:05.647895    1245 [not-set] ZookeeperEpochStore.cpp:174] completionStatus() Check failed: false
handle_fatal_signal(): Caught coredump signal 6
    @ 000056005206ebdd facebook::logdevice::handle_fatal_signal(int)
                       -> /home/logdevice/logdevice/external/folly/folly/io/async/AsyncPipe.cpp
    @ 00005600517f3570 coredump_signal_handler(int)`

Default zookeeper config used.

Logdevice cluster config:
`{
    "cluster": "test",
    "nodes": [
        {
            "node_id": 0,
            "host": "10.0.4.34:16111",
            "gossip_port": 16112,
            "generation": 1,
            "roles": [ "sequencer", "storage" ],
            "sequencer": true,
            "storage": "read-write",
            "num_shards": 1
        },
        {
            "node_id": 1,
            "host": "10.0.4.167:16111",
            "gossip_port": 16112,
            "generation": 1,
            "roles": [ "sequencer", "storage" ],
            "sequencer": true,
            "storage": "read-write",
            "num_shards": 1
        }
    ],
    "internal_logs": {
        "config_log_deltas": {
            "replicate_across": {
                "node": 2
            }
        },
        "config_log_snapshots": {
            "replicate_across": {
                "node": 2
            }
        },
        "event_log_deltas": {
            "replicate_across": {
                "node": 2
            }
        },
        "event_log_snapshots": {
            "replicate_across": {
                "node": 2
            }
        }
    },
    "metadata_logs": {
        "nodeset": [0,1],
        "replicate_across": { "node": 2 }
    },
    "zookeeper": {
        "quorum": [
            "10.0.1.114:2181"
        ],
        "timeout": "30s"
    }
}`

Note:
Issue doesn't reproduce if logdeviced is linked with static zookeeper library (zookeeper_mt.a)

**Comment by shixiao** [comment]
@Krestol, could you please provide some more detail on the Zookeeper setup and ACL you used? In addition, are you able to create a znode such as `/logdevice/logs` using the zkCli?

**Comment by Krestol** [comment]
I use the simplest zookeeper installation with default zoo.conf. I don't use any specific ACL.
I'm able to create /logdevice/logs via zkCli

**Comment by Krestol** [comment]
It seems I have found the cause of this issue
https://github.com/facebookincubator/LogDevice/pull/118

**Comment by MohamedBassem** [comment]
Your fix landed. Thanks again @Krestol for the fix!
