### ISSUE TITLE
Сontainer stops working after some period of time

### ISSUE THREAD

**Issue by Krestol** [facebookincubator/LogDevice#120]
Steps:
1. Start cluser
2. ldshell -c $LOGDEVICE_CONFIG logs create --replicate-across "node: 2" --backlog "259200s" --from 1 --to 100 /test_logs
3. echo 1 | ldwrite $LOGDEVICE_CONFIG -l 1
4. ldshell -c $LOGDEVICE_CONFIG logs create --replicate-across "node: 2" --backlog "10s" --from 101 --to 200 /test_logs_2
5. echo 101_1 | ldwrite $LOGDEVICE_CONFIG -l 101

The attached archive contains cluster config and logdevice log
[logdevice-crash.zip](https://github.com/facebookincubator/LogDevice/files/3698252/logdevice-crash.zip)

**Comment by MohamedBassem** [comment]
The same bug exists in the FileEpochStore which is used by our localhost cluster.

Managed to repro by starting a localhost cluster with `num-workers=2` and then applying the steps in the task.

**Comment by MohamedBassem** [comment]
Your PR got merged, thanks @Krestol for yet another fix!
