### ISSUE TITLE
Is it possible to add a dockerhub mirror address under release

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [facebookincubator/LogDevice#124]
Is it possible to add a dockerhub mirror address under [release](https://github.com/facebookincubator/LogDevice/releases)? 

:)

**Comment by MohamedBassem** [comment]
Publishing docker images for release versions is something on my TODO list. I’ll push one manually today until I automate the process :)

**Comment by MohamedBassem** [comment]
Just pushed LogDevice 2.43.7 to dockerhub: https://hub.docker.com/r/facebookincubator/logdevice/tags

I also cut multiple new releases. The last stable one is 2.45.1 which I'm currently building to push to dockerhub as well.

**Comment by MohamedBassem** [comment]
2.45.1 pushed. Prefer using this one over 2.43.X :)
