### ISSUE TITLE
Integrate with open source monitoring/alerting

### ISSUE THREAD

**Issue by Zepheus** [facebookincubator/LogDevice#13]
LogDevice exports a lot of stats which are currently only available through the Admin commands (`stats`).

We should consider integrating with Prometheus, Influx or other tooling.
The plugin system is already in place, but has no implementation yet:

https://github.com/facebookincubator/LogDevice/blob/debb8abc5794b909989a153843f2982db4ab7be9/logdevice/common/PluginPack.h#L81

**Comment by sh00s** [comment]
#37 is figured out far enough (`StatsPublisherFactory` is now a separate plugin) that this should be viable now. The plugin implementation should derive from `StatsPublisherFactory`:
https://github.com/facebookincubator/LogDevice/blob/5e4cf130b8e90c6fc78b79e4a2cfbf25c7a62cfd/logdevice/common/plugin/StatsPublisherFactory.h#L24

The `StatsPublisherFactory` instance should create a derivative of `StatsPublisher`, which should then implement the `publish()` method that would publish the stats to an external system:
https://github.com/facebookincubator/LogDevice/blob/5e4cf130b8e90c6fc78b79e4a2cfbf25c7a62cfd/logdevice/common/StatsPublisher.h#L31

**Comment by zhaohaidao** [comment]
Is there someone working on it?

I want to try to export the stats to prometheus.

**Comment by ylectric** [comment]
@zhaohaidao, I don't think we've someone on it, so feel free to go ahead, we'd appreciate a PR :)

**Comment by zhengxiaochuan-3** [comment]
Looking forward to this  [https://github.com/MohamedBassem/logdevice-prometheus](https://github.com/MohamedBassem/logdevice-prometheus)
@MohamedBassem
