### ISSUE TITLE
commont_test failed

### ISSUE THREAD

**Issue by Krestol** [facebookincubator/LogDevice#131]
Steps:
Run common_test executable

Actual result:
Failed tests:
DataSizeRequestTest.DeadEndWithPermanentErrors1
DataSizeRequestTest.DeadEndWithPermanentErrors2
DataSizeRequestTest.Failed

Expected result:
All tests passed

**Comment by Krestol** [comment]
Review, please the proposed fix https://github.com/facebookincubator/LogDevice/pull/132

**Comment by MohamedBassem** [comment]
The PR got merged. Thanks again @Krestol!
