### ISSUE TITLE
Read data from LogDevice  slow

### ISSUE THREAD

**Issue by jls502** [facebookincubator/LogDevice#157]
Hi, there.  I have 180 clients writing to a logid at the same time, and each client uses a bufferWriter to batch write with a 1 second tigger. The write volume in half an hour is about 40MB. It takes 14 seconds to read this 40MB of data from this logid.  I dont know what happened, is this normal？

**Comment by AhmedSoliman** [comment]
Can you share details on how your cluster is configured?
Things that matter:
- What’s the average payload size per message?
- Are you running on flash or hard drives.
- Do you know how many messages per second you are writing?
- Are these reads realtime or backfills? Are your readers following the tail?

Also, if you can share your configuration file in a paste that would be great (also the client settings that you pass to ClientFactory

**Comment by AhmedSoliman** [comment]
Are you using the default value for the setting `client-read-buffer-size`? Can you configure your reader to use a much higher value (based on how much memory do you have available for the client)

**Comment by MohamedBassem** [comment]
One recommendation that worked for @zhengxiaochuan-3 is to enable sequencer batching. It's basically a buffered writer that gets filled on sequencers buffering writes coming from different clients.
You can enable it by adding:

```
sequencer-batching = "true",
```
to the server settings. By default it buffers for 1 second, but it's configurable with the setting `sequencer-batching-time-trigger`. Check sequencer batching settings here: https://logdevice.io/docs/Settings.html.

**Comment by jls502** [comment]
@MohamedBassem @AhmedSoliman   yeah, after the `sequencer-batching = "true" ` configuration is configured on the server, the problem of slow reading is fixed. 
    I closed the issue, thx a lot
