### ISSUE TITLE
Question: Why hand write protocol ?

### ISSUE THREAD

**Issue by prehistoric-penguin** [facebookincubator/LogDevice#16]
I find there are two many hand write protocol files in logdevice/common.
Doesn't fbthrift or any other RPC meet the demand here?

**Comment by AhmedSoliman** [comment]
LogDevice protocol was designed with streaming in mind. That was not something available in thrift/fbthrift when we originally looked into it. The protocol allows the client and servers to exchange a reading sliding window changes to efficiently move the reading cursors remotely. This also allows for back pressure control if the client local buffers are full, server will pause sending records accordingly.

While handcrafted protocol codecs are not the most pleasing to implement, they offer us a great deal of control over memory and CPU efficiency. Both are very important for LogDevice scalability .
