### ISSUE TITLE
when set "num_shards": 12 ,  ldshell connect error 

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [facebookincubator/LogDevice#172]
I want to expand my cluster, add two nodes to it.

Frist I set "num_shards": 1  by mistake, ldshell can connect to cluster.

But ,I Have 12 disks, and I should set  "num_shards": 12

when I  set it to "num_shards": 12, ldshell connect error :

`Logging to /tmp/ldshell-19dnneh4
Logging Level: WARNING
Cannot connect to logdevice cluster!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/python_nubia-0.2b1-py3.6.egg/nubia/internal/io/eventbus.py", line 24, in react
    self.on_connected(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ldshell-0.1-py3.6.egg/ldshell/logdevice_context.py", line 116, in on_connected
    raise e
  File "/usr/local/lib/python3.6/dist-packages/ldshell-0.1-py3.6.egg/ldshell/logdevice_context.py", line 112, in on_connected
    self._client = self.build_client()
  File "/usr/local/lib/python3.6/dist-packages/ldshell-0.1-py3.6.egg/ldshell/logdevice_context.py", line 86, in build_client
    settings=default_settings,
logdevice.client.LogDeviceError: (logdevice.client.status.INVALID_CONFIG, 'INVALID_CONFIG', 'INVALID_CONFIG: various errors in config contents')
`		

              

> {
> 			"node_id": 6,
> 			"host": "10.32.24.6:16111",
> 			"gossip_port": 16112,
> 			"generation": 1,
> 			"roles": ["sequencer", "storage"],
> 			"sequencer": false,
> 			"storage": "disabled",
> 			"num_shards": 12
> 		},
> 		{
> 			"node_id": 7,
> 			"host": "10.32.212.24:16111",
> 			"gossip_port": 16112,
> 			"generation": 1,
> 			"roles": ["sequencer", "storage"],
> 			"sequencer": false,
> 			"storage": "disabled",
> 			"num_shards": 12
> 		},

My conf JSON fmt is right, What I missed?

**Comment by MohamedBassem** [comment]
Do you mind providing the full json?

**Comment by zhengxiaochuan-3** [comment]
{
	"cluster": "LogHouse-baymax-go-gzqy",
	"server_settings": {
		"rocksdb-auto-create-shards": true,
		"rocksdb-read-find-time-index": true,
		"write-find-time-index": true,
		"zk-create-root-znodes": false,
		"rocksdb-partition-duration": "60min",
		"rocksdb-partition-size-limit": "12G",
		"self-initiated-rebuilding-grace-period": "86400s",
		"sequencer-batching": true,
		"sequencer-batching-time-trigger": "10s"
	},
	"nodes": [{
			"node_id": 0,
			"host": "10.32.152.37:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": true,
			"storage": "read-write",
			"num_shards": 1
		},
		{
			"node_id": 1,
			"host": "10.32.152.32:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": true,
			"storage": "read-write",
			"num_shards": 1
		},
		{
			"node_id": 2,
			"host": "10.32.152.2:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": true,
			"storage": "read-write",
			"num_shards": 1
		},
		{
			"node_id": 3,
			"host": "10.32.152.17:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": true,
			"storage": "read-write",
			"num_shards": 1
		},
		{
			"node_id": 4,
			"host": "10.32.24.3:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": false,
			"storage": "disabled",
			"num_shards": 12
		},
		{
			"node_id": 5,
			"host": "10.32.22.7:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": false,
			"storage": "disabled",
			"num_shards": 12
		},
		{
			"node_id": 6,
			"host": "10.32.24.6:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": false,
			"storage": "disabled",
			"num_shards": 12
		},
		{
			"node_id": 7,
			"host": "10.32.212.24:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": false,
			"storage": "disabled",
			"num_shards": 12
		},
		{
			"node_id": 8,
			"host": "10.32.164.27:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": false,
			"storage": "disabled",
			"num_shards": 12
		},
		{
			"node_id": 9,
			"host": "10.32.206.23:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": false,
			"storage": "disabled",
			"num_shards": 12
		},
		{
			"node_id": 10,
			"host": "10.32.172.43:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": false,
			"storage": "disabled",
			"num_shards": 12
		},
		{
			"node_id": 11,
			"host": "10.32.166.6:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": false,
			"storage": "disabled",
			"num_shards": 12
		},
		{
			"node_id": 12,
			"host": "10.32.180.43:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": false,
			"storage": "disabled",
			"num_shards": 12
		},
		{
			"node_id": 13,
			"host": "10.32.238.46:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": false,
			"storage": "disabled",
			"num_shards": 12
		},
		{
			"node_id": 14,
			"host": "10.32.182.31:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": false,
			"storage": "disabled",
			"num_shards": 12
		},
		{
			"node_id": 15,
			"host": "10.32.208.45:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": false,
			"storage": "disabled",
			"num_shards": 12
		},
		{
			"node_id": 16,
			"host": "10.32.212.7:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": false,
			"storage": "disabled",
			"num_shards": 12
		},
		{
			"node_id": 17,
			"host": "10.32.172.25:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": false,
			"storage": "disabled",
			"num_shards": 12
		},
		{
			"node_id": 18,
			"host": "10.32.210.24:16111",
			"gossip_port": 16112,
			"generation": 1,
			"roles": ["sequencer", "storage"],
			"sequencer": false,
			"storage": "disabled",
			"num_shards": 12
		}
	],
	"internal_logs": {
		"config_log_deltas": {
			"replicate_across": {
				"node": 3
			}
		},
		"config_log_snapshots": {
			"replicate_across": {
				"node": 3
			}
		},
		"event_log_deltas": {
			"replicate_across": {
				"node": 3
			}
		},
		"event_log_snapshots": {
			"replicate_across": {
				"node": 3
			}
		}
	},
	"metadata_logs": {
		"nodeset": [0, 1, 2, 3],
		"replicate_across": {
			"node": 3
		}
	},
	"zookeeper": {
		"quorum": [
			"10.32.160.15:2183",
			"10.32.160.17:2183",
			"10.32.160.19:2183",
			"10.32.160.22:2183",
			"10.32.160.45:2181"
		],
		"timeout": "30s"
	}
}

**Comment by zhengxiaochuan-3** [comment]
4~18 are new nodes  I expanded

**Comment by MohamedBassem** [comment]
Oh, currently LogDevice doesn't support running with clusters that have mixed number of shards. All the nodes must have the exact number of shards otherwise we consider the config as invalid.

**Comment by zhengxiaochuan-3** [comment]
Ok, thank you
