### ISSUE TITLE
Inconsistent column type for node_id in Sequencer and Nodes table

### ISSUE THREAD

**Issue by xuning97** [facebookincubator/LogDevice#179]
the first one is of type INTEGER, map to int
<img width="580" alt="9a8df2aac97099772bbccce8e94baf2" src="https://user-images.githubusercontent.com/1954442/78127628-190cf100-7447-11ea-8a51-fd06c56f5182.png">

the second one is of type BIGINT, map to long
<img width="456" alt="c9a4763c19560f4204f0a1f455522c4" src="https://user-images.githubusercontent.com/1954442/78127637-1ca07800-7447-11ea-8dc4-671b84116603.png">

**Comment by MohamedBassem** [comment]
This should be fine. This is mostly used for `ldquery` and INT translates to an 8-byte integer which is way more than enough for any size LogDevice supports.

**Comment by xuning97** [comment]
Will it be ok if i submit a simple PR to make both of them DataType::INTEGER?

**Comment by MohamedBassem** [comment]
Yeah definitely, I'd happily accept that :)
