### ISSUE TITLE
Settings abort-on-failed-check, abort-on-failed-catch and external-loglevel don't correctly subscribe to settings update

### ISSUE THREAD

**Issue by tau0** [facebookincubator/LogDevice#183]
### Intro
LogDevice has a lot of [settings](https://logdevice.io/docs/Settings.html). Some of the settings require a restart for the daemon, while others don't (as noted in the `Notes` section). It's however up to the developer to subscribe and react to setting changes to make the settings actually not require a restart.

### Problem
The settings [abort-on-failed-check](https://github.com/facebookincubator/LogDevice/blob/master/logdevice/common/settings/Settings.cpp#L802-L810), [abort-on-failed-catch](https://github.com/facebookincubator/LogDevice/blob/master/logdevice/common/settings/Settings.cpp#L811-L819) and [external-loglevel](https://github.com/facebookincubator/LogDevice/blob/master/logdevice/common/settings/Settings.cpp#L3646-L3652) are marked as don't require restart however their usage doesn't correctly react to the setting updates. This issue is about changing the usage of those settings to react to setting updates.

### Code Pointers

- Usage of the settings: [here](https://github.com/facebookincubator/LogDevice/blob/master/logdevice/common/Processor.cpp#L150-L161) which is invoked from [here](https://github.com/facebookincubator/LogDevice/blob/master/logdevice/common/Processor.cpp#L248).
- Processor's existing settings subscription: [here](https://github.com/facebookincubator/LogDevice/blob/master/logdevice/common/Processor.cpp#L811).

**Comment by MohamedBassem** [comment]
@ankitdixit Implemented this already! :)
