### ISSUE TITLE
Stream Processing - CEP -  Siddhi SQL - Feature Request

### ISSUE THREAD

**Issue by mkharibalaji** [facebookincubator/LogDevice#19]
Hi Team,
           Since LogDevice is doing Stream processing can we have a Complex event processing like Siddhi SQL 
https://wso2.github.io/siddhi/

**Comment by AhmedSoliman** [comment]
LogDevice itself is a building block that can be used in stream processing systems. However, it only on focuses on data storage and delivery. The processing has to be done by another layer like Apache Samza.

LogDevice currently doesn't have language bindings for Java. This is something that we might look into in the future. For now, feel free to build wrapper Java API using JNI on top of our existing C++ client library.

**Comment by mkharibalaji** [comment]
Thanks @AhmedSoliman
