### ISSUE TITLE
ModuleNotFoundError: No Module named 'libfb'

### ISSUE THREAD

**Issue by xuning97** [facebookincubator/LogDevice#192]
With latest code, when I run ldshell, I got an error like the following,

![image](https://user-images.githubusercontent.com/1954442/84456475-9f894e80-ac92-11ea-85a8-4cffca337f03.png)

It might have something to do with fbthrift compilation? I compile with -Dthriftpy3=ON option, and  python 3.6.9, there is no python2 installed.

When -Dthriftpy3=ON is enabled, in many cases, the pyd/pyx file will failed to generate during the compile process and I have to manually make the py3-target. 

If -Dthriftpy3=ON is not enabled, ldshell doesn't work?

**Comment by ylectric** [comment]
Hey @xuning97, it's not related to Thrift, but is related to an internal library that we accidentally used in a recent commit. I'm gonna send a fix.
