### ISSUE TITLE
LogDevice build failing on Ubuntu bionic

### ISSUE THREAD

**Issue by Ahiknsr** [facebookincubator/LogDevice#193]
### System Info

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

**Building on the below commit**
$ git show --oneline -s
b4358901 (HEAD -> master, origin/master, origin/HEAD) Prepare for deletion of external folder by cleaning headers

**Build Command**
:~/LogDevice/_build$ make -j $(nproc)

**Build Error**
Scanning dependencies of target common_test
[ 50%] Linking CXX shared module ../../../../python-out/logdevice/ops/admin_command_client.so
[ 50%] Building CXX object lib/CMakeFiles/ldclient.dir/ClientSettings.cpp.o
[ 50%] Building CXX object lib/CMakeFiles/ldclient.dir/ClientSettingsImpl.cpp.o
/usr/bin/ld: ../../../../lib/libadmin-cpp2.a(AdminAPIAsyncClient.cpp.o): relocation R_X86_64_PC32 against symbol `_ZNK5folly5RangeIPKcE4sizeEv' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
[ 50%] Building CXX object lib/CMakeFiles/ldclient.dir/ClientWorker.cpp.o
ops/py_extensions/admin_command_client/py/CMakeFiles/logdevice_admin_command_client_python.dir/build.make:171: recipe for target 'python-out/logdevice/ops/admin_command_client.so' failed
make[2]: *** [python-out/logdevice/ops/admin_command_client.so] Error 1
CMakeFiles/Makefile2:5278: recipe for target 'ops/py_extensions/admin_command_client/py/CMakeFiles/logdevice_admin_command_client_python.dir/all' failed
make[1]: *** [ops/py_extensions/admin_command_client/py/CMakeFiles/logdevice_admin_command_client_python.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by MohamedBassem** [comment]
Hi, please use this build instructions (https://logdevice.io/docs/next/Installation.html#create-a-build-directory) and this should resolve your issue. This is the up to date documentation, we will make it the default soon.

**Comment by Ahiknsr** [comment]
Hey, Thanks for the pointer. I have followed the up-to date instructions and now I'm seeing the below error. Can you please help. (i installed the python dependencies, executed the cmake and make in virtualenv as per the docs) 

gen-py3/iobuf/services_reflection.pxd:8:0: 'thrift/py3/reflection.pxd' not found
[ 81%] Building CXX object thrift/lib/py3/CMakeFiles/thrift-py3-server-py3.dir/cybld/thrift/py3/server.cpp.o
thrift/lib/py3/test/CMakeFiles/iobuf-services-py3.dir/build.make:61: recipe for target 'thrift/lib/py3/test/gen-py3/iobuf/services.cpp' failed
make[5]: *** [thrift/lib/py3/test/gen-py3/iobuf/services.cpp] Error 1
make[5]: *** Deleting file 'thrift/lib/py3/test/gen-py3/iobuf/services.cpp'
CMakeFiles/Makefile2:1830: recipe for target 'thrift/lib/py3/test/CMakeFiles/iobuf-services-py3.dir/all' failed
make[4]: *** [thrift/lib/py3/test/CMakeFiles/iobuf-services-py3.dir/all] Error 2


detailed logs [here](https://gist.github.com/Ahiknsr/593c1ab642cbc9dc6660b7696b8902cd)

**Comment by MohamedBassem** [comment]
Yeah, seems like our master build got broken 20 hours ago. You should be able to get a successful build until this commit (4919ad8ea1a6e1b8647dadffdc8875ea5561de88) (the one before the last one).

**Comment by Ahiknsr** [comment]
Thanks. I tried the build with 4919ad8 and it worked.
