### ISSUE TITLE
logdevice/build_tools/fedora.deps file doesn't exist

### ISSUE THREAD

**Issue by dmitris** [facebookincubator/LogDevice#194]
The installation instructions on https://logdevice.io/docs/Installation.html (from https://github.com/facebookincubator/LogDevice/blob/master/website/versioned_docs/version-2.46.5/installation.md) say:
> ** Fedora only - Install packages. **
>
> sudo yum install $(cat LogDevice/logdevice/build_tools/fedora.deps)

However, there's no `fedora.deps` file in the repository.

**Comment by MohamedBassem** [comment]
I'll close this issue, please re-open it if you have any more questions.
