### ISSUE TITLE
The log range specified must be positive 62-bit with start smaller or equal than end of range, supplied range is 0..200000

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [facebookincubator/LogDevice#197]
E0623 19:06:39.770100    1108 [logdevice:WG13] LogsConfigTree.cpp:338] isRangeValid() invalid log range attribute for Log Group: "push_trace".The log range specified must be positive 62-bit with start smaller or equal than end of range, supplied range is **0..200000**

![image](https://user-images.githubusercontent.com/10624990/85396789-ede8f800-b584-11ea-85a9-ab855e527694.png)

**Comment by MohamedBassem** [comment]
That's interesting but unfortunately not enough debugging information to figure out what's going on. Was it a oner time log line or is continuously being printed? Any idea how to repro?

**Comment by zhengxiaochuan-3** [comment]
> That's interesting but unfortunately not enough debugging information to figure out what's going on. Was it a oner time log line or is continuously being printed? Any idea how to repro?

I create this loggroup from 0 to 200000 by ldshell for the first time and get error , and then I create it again from 1 to 200000.
I think this opt can repor.

**Comment by AhmedSoliman** [comment]
Log ID `0` is not allowed, that's what a "positive" part of the error message is trying to tell you here.
