### ISSUE TITLE
Will sequencer become a bottleneck for large size record with high throughput

### ISSUE THREAD

**Issue by xuning97** [facebookincubator/LogDevice#202]
From the doc, I think for a single log, there is only one sequencer in a sequencer node.
If the network condition for that node is not good, or in case the log write frequency and size is too high, will this sequencer become a bottleneck?

**Comment by MohamedBassem** [comment]
Yes that’s correct, there’s only one sequencer per log. Bad networking on the sequencer can easily be your bottleneck for multiple reasons:
1. Not only does the sequencer receive the records, but it also have to send X copies out to other nodes where X is your replication property.
2. Bad networking may mean that the sequencer will take more time to replicate the records, which means an increase in append latency, while will result into the sequencers buffers filling up and rejecting any new writes.

There are multiple ways you can get around that:
1. You can enable a feature that’s called chain sending. Where the sequencer only sends one copy out and then each storage node sends another copy in a chain until the replication property is satisfied. This reduces networking overhead on the sequencer however you pay that cost in an increased append latency.
2. You can enable sequencer batching + compression which means that the sequencer doesn’t replicate each records individually but batches and compress them before replicating them. Again, you pay the cost in terms of more append latency for batching.
3. If you don’t care about the ordering of the records, you can always shard across more logs.

But in general, yes. The sequencer node can become your bottleneck if your throughput is high enough.

**Comment by xuning97** [comment]
Hi, will it be a valid design to let sequencer generate id only, and then let the writer performs the write directly?

**Comment by MohamedBassem** [comment]
If there's a single writer to the log, we can even do the sequencing on that client. If there are multiple, the sequnecer will issue LSNs but also will have to coordinate between the writers to move the Last known good (LNG) pointer, do the releases, etc.

So yeah, I think it's possible but it will a signficant amount of complexity to the system so it needs to be justified.

**Comment by MohamedBassem** [comment]
Maybe @mcrnic can expand more on this as I think we had some design for a similar thing before?
