### ISSUE TITLE
Conditional add question

### ISSUE THREAD

**Issue by mfateev** [facebookincubator/LogDevice#208]
Hi, I wasn't able to find from the documentation and it looks like the Slack forum is dead. 

if it is possible to perform conditional writes? In my case, my application maintains the LSN, and to avoid race conditions needs to make every append conditional on the last LSN used.

**Comment by MohamedBassem** [comment]
Responded on slack, but for reference here's the response:

> We have a feature in LogDevice that’s called Tail Optimized logs which allows you to do conditional writes based on LSNs and record values. However, we never fully completed the implementation as the project got deprioritized on our side and I’m actually working on deprecating the support for it in the codebase. So unfortunately, this is currently not supported.

**Comment by mfateev** [comment]
Thank you!
