### ISSUE TITLE
I want to integrate Kubernetes with VirtualLog. 

### ISSUE THREAD

**Issue by Mehmoodulhassan104** [facebookincubator/LogDevice#213]
As in the paper title "Virtual Consensus in Delos"
the concept of VirtualLog is discussed and implemented. That is actually implemented by Facebook.  See below figure

![image](https://user-images.githubusercontent.com/72472501/99574686-8632be00-29f9-11eb-9b54-483f3d0cc299.png)

 VirtualLog code is available openly? 
Actually i want to use VirtualLog with Kubernetes and prometheus. So, I want to know how it work actually and how i can integrate it with kubernetes and prometheus. 
#virtualLog #LogDevice #Facebook

**Comment by AhmedSoliman** [comment]
I don't think VirtualLog is open-source. LogDevice is also now archived in open-source, the team decided that we will not continue to support the open-source version but the code will remain to be available for those interested in researching the design decisions.
