### ISSUE TITLE
Is this project no longer maintained?

### ISSUE THREAD

**Issue by daleiz** [facebookincubator/LogDevice#216]

**Comment by MohamedBassem** [comment]
Yes. The project is now archived and won't receive further updates.

**Comment by daleiz** [comment]
Why it is archived?   is Facebook  still using it internally?

**Comment by MohamedBassem** [comment]
Facebook is still using it internally however the team decided to no longer maintain the open source version. This is mostly because LogDevice will start relying on some internal FB infra that are not available externally which will make maintaining the open source version not feasible.

**Comment by daleiz** [comment]
I am very sad to hear that. In fact, we just recently planned to develop our new project based on LogDevice. The current open source version is stable enough? Can it be used in production? Could you please give me some advices about this project? Thank you very much!

**Comment by motohedgehog** [comment]
@daleiz former LogDevice team member here. The current version is indeed stable enough as this repo mirrors the internal development. @MohamedBassem, do you think you guys could make a farewell GtiHub release for those who want to use LogDevice outside Facebook?

**Comment by MohamedBassem** [comment]
@ylectric I made sure that the `master` branch is working (still pending some ldshell fixes). However, it being working doesn't mean it's production-ready. There isn't any company I'm aware of that uses LogDevice's open source version in a production environment so I honestly would recommend against using it in production. Specially that now if an issue arises, we're not going to be able to send fixes for it.

**Comment by AhmedSoliman** [comment]
Yes, sorry that we had to do this but few team members ended up maintaining the open-source version and few number of people showed interest in using LogDevice outside Facebook. This is understandable since LogDevice is tuned for a workload that most people don't have. 

We will leave the code there to inspire the community with some of the design choices but we will not be working any further on that.

**Comment by zhengxiaochuan-3** [comment]
We build a huge collection&analysis log system based on Logdevice , and It is very stable. @daleiz  
Logdevice is production-ready on our case.

**Comment by daleiz** [comment]
@zhengxiaochuan-3 Thanks for your reply! I'm very happy to hear that. Could you please share more about your use case? 
- What is the approximate size of your logdevice cluster? 
- How long has your logdevice service been running?
- Based on your experience , is  logdevice cluster easy to manage and maintain?

**Comment by zhengxiaochuan-3** [comment]
@daleiz 

1. We have 10 logdevice clusters, and the biggest cluster has 20 nodes;  About 2 trillion rows of logs being written to these clusters  per day. 
2. About one year.
3. Yes.

**Comment by daleiz** [comment]
Thanks  again for your enthusiastic response! Since this project is no longer maintained，could you please give me your email address for further communication about logdevice? If you don't want  to post your email address here, my email address is bencollins131@gmail.com , and  I am looking forward to hearing from you!

**Comment by zhengxiaochuan-3** [comment]
@daleiz 

Let's talk in here?   https://app.slack.com/client/TPLJ0G6CE/CP6TF11NF/thread/CP6TF11NF-1586501270.009300

**Comment by daleiz** [comment]
@zhengxiaochuan-3

OK,  I just send a message in this slack channel.
