### ISSUE TITLE
Add FBThrift to LogDevice-oss builds

### ISSUE THREAD

**Issue by calebmarchent** [facebookincubator/LogDevice#24]
A number of additional service integrations are based on FBThrift, to allow these to be added to the open source version; we need FBThift in the LogDevice open source build.

Notes on the investigation so far:

FBThrift requires Wangle; Wangle wants the header files and config of folly to be in the "installed" structure; where the generated headers and source headers are in one place
To achieve this; we need to create the concept of a "ROOT_DIR", as we have in cross compilation environments like buildroot or Yocto. CMake supports this through the configuration of CMAKE_FIND_ROOT_PATH; we need to install folly into this and then pass the location to the CMake config for wangle ... and it builds successfully.

**Comment by calebmarchent** [comment]
I have my first shot at building the FBThrift as an external project within the LogDevice-OSS tree:
https://github.com/calebmarchent/LogDevice/tree/integ_fbthrift

Bit of tidying to do and then can try using it for something.

**Comment by calebmarchent** [comment]
Update:
* The Thrift compiler is integrated into the LogDevice build; C++ versions of the admin API are compiled.
Next steps:
* Get Thrift to compile interface for Python
* Link both C++ and Python Thrift libraries and test the admin API service.

**Comment by calebmarchent** [comment]
First PR created; compiles Folly.executor Cython wrapper: https://github.com/facebook/folly/pull/992

**Comment by calebmarchent** [comment]
Folly.executor Cython wrapper landed; though folly must be built with option PYTHON_EXTENSIONS enabled. Now revising Thrift implementation with the "learnings" from the Folly work.

**Comment by Ikhbar-Kebaa** [comment]
website/siteConfig.js/https:/www.facebook.com/Keba06

**Comment by calebmarchent** [comment]
This is done; LogDevice builds include and use FBThrift and FBThrift-py3
