### ISSUE TITLE
Deprecate logdevice/common/configuration/Log.h

### ISSUE THREAD

**Issue by Zepheus** [facebookincubator/LogDevice#27]
The data structures used from `logdevice/common/configuration/Log.h` are deprecated in favor of the new structures in `logdevice/common/configuration/logs/LogsConfigTree.h`.

All of the server/common code has been cleaned up already, but quite a few tests still use this.

**Comment by david-y-lam** [comment]
typo in your post:

`LogsConfigTree.h` instead of `LogConfigTree.h`

**Comment by david-y-lam** [comment]
Should be good to close now

**Comment by Zepheus** [comment]
Thank you David for cleaning up this tech-debt!
