### ISSUE TITLE
Add endian awareness to the protocol

### ISSUE THREAD

**Issue by Zepheus** [facebookincubator/LogDevice#28]
Right now, most of the message serialization uses `memcpy` directly to construct the over-the-wire payload.

Whenever these structures include integers, they are implicitly encoded in the machine's endianness. This will cause a binary incompatibility on machines that do not provide flexible endianness per process (e.g. MIPS?)

We should abstract this away using helper functions from the `htons, htonl, ntohs, ntohl` family.
Alternatively, we could use flatbuffers and gate this under protocol negotiations. This would greatly speed up adding message types in the future.

**Comment by AhmedSoliman** [comment]
We discussed that and we don't think this is something we should be doing at the moment, it's a big change with little value. I will close this for now, but we can re-visit this in the future.
