### ISSUE TITLE
Figure out how to build / load / combine plugins

### ISSUE THREAD

**Issue by Zepheus** [facebookincubator/LogDevice#37]
Right now, there is a `PluginPack` that registers a single binary (`.so`) for different purposes.
We need to figure out:
- How to separate each part into a separate binary. E.g. I'd like to use Prometheus for logging and ElasticSearch for tracing. It should allow combinations flexibly.
- How to build plugins in open source. Should we have a sub-directory? Separate cmake files for each?  Separate repositories?

**Comment by sh00s** [comment]
Separated #56 and #57 out of this

**Comment by sh00s** [comment]
This is mostly done. I added documentation in 84fbb0ade491aa5befd8cd7fbcf39ba22a6efc2a to explain how to write new plugins, and filed the follow-ups mentioned above for the remaining parts.
