### ISSUE TITLE
Chain LogDevice documentation pipeline together in CircleCI Jobs

### ISSUE THREAD

**Issue by calebmarchent** [facebookincubator/LogDevice#45]
With PR https://github.com/facebookincubator/LogDevice/pull/44, documentation is reproducible from source, with the following process:

1. Build LogDevice on Ubuntu Bionic machine (additional doxygen package required)
1. Run 'make docs' which will update generated markdown files `settings.md`, `ldquery.md` and doxygen generated client API documentation under `website/static/api`.
1. Check in updated files to source control, create a PR and integrate which triggers...
1. Docusaurus run to update website

To keep things up-to-date, with no human intervention the manual steps need to be automated:

Run make docs as part of the build job under Ubuntu Bionic CircleCI build, archiving the output of the `build` CircleCI job and making available to the deploy-website job; which using this as input updates the website
At this point generated files in `website/static/api` to be removed as they are output files rather than source files. 

There is a question over settings.md and ldquery.md; as these are legible when browsed in GitHub; it might make sense to leave the generated files under source control? 
If we do follow this option, add a test to ensure that any changes that update documentation include the corresponding update to those generated files; else we risk having different documents on the website to those viewed on master.

**Comment by sh00s** [comment]
> add a test to ensure that any changes that update documentation include the corresponding update to those generated files

That's a great idea!

**Comment by calebmarchent** [comment]
Implemented in:
https://github.com/facebookincubator/LogDevice/pull/47
