### ISSUE TITLE
Publish a docker image on dockerhub

### ISSUE THREAD

**Issue by MohamedBassem** [facebookincubator/LogDevice#5]
Building the logdevice's docker image (and logdevice itself) takes too long, it would be great if you integrate the repo with docker hub to automatically build and publish images out of master (or any stable branch).

**Comment by AhmedSoliman** [comment]
Currently there are a number of issues that prevent LogDevice from running properly in a docker instance. The Dockerfile was written to validate logdevice open-source builds against a reliably clean environment. It was not meant to be used (at least for now) as a viable way of running the daemon.

Until we get there, we will not be publishing images to docker hub nor recommending docker as a method of running logdevice either for test or prod.
