### ISSUE TITLE
Install all Python modules with setup.py; rather than copying directly with CMake

### ISSUE THREAD

**Issue by calebmarchent** [facebookincubator/LogDevice#52]
First attempt at installation of Python modules of LogDevice was implemented by determining the dist directory, setting variable PYTHON_MODULE_INSTALL_PREFIX and then installing files into the calculated location. This method is convoluted and goes against the preferred method for packaging Python modules using distutils and setuputils. 
For ldshell; we created a setup.py and then install it with a straight forward command line call:

https://github.com/facebookincubator/LogDevice/blob/2c0d9d5d9a38dfc5e60886acabc0a036eb43031e/logdevice/ops/CMakeLists.txt#L10

Switch to this method for install of all Python modules, including: 
* LogDevice client binding
* Admin client 
* LD Query

To find all examples search code for PYTHON_MODULE_INSTALL_PREFIX

**Comment by AhmedSoliman** [comment]
This is now done.
