### ISSUE TITLE
LogDevice-OSS build failing...

### ISSUE THREAD

**Issue by calebmarchent** [facebookincubator/LogDevice#53]
We get the following error while building:
```
/usr/bin/ld: ../folly-prefix/src/folly-build/folly/libfollybenchmark.a(Benchmark.cpp.o): undefined reference to symbol '_ZN6google14FlagRegistererC1IbEEPKcS3_S3_PT_S5_'
//usr/lib/x86_64-linux-gnu/libgflags.so.2.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
examples/CMakeFiles/ld-dev-cluster.dir/build.make:344: recipe for target 'bin/ld-dev-cluster' failed
make[2]: *** [bin/ld-dev-cluster] Error 1
CMakeFiles/Makefile2:1916: recipe for target 'examples/CMakeFiles/ld-dev-cluster.dir/all' failed
make[1]: *** [examples/CMakeFiles/ld-dev-cluster.dir/all] Error 2
```

Looks like this failure might have started occurring around the following commit: https://github.com/facebookincubator/LogDevice/commit/63333fc2820da39e7085d06671f9cfeb3c978743

**Comment by AhmedSoliman** [comment]
Do they require a new gflags version or something?

**Comment by calebmarchent** [comment]
Looks like the specific change that introduced the issue is https://github.com/facebook/folly/commit/dacf5bc601b03648d3da23eb9046e244ff5c51f2

Where in introducing the ability to specify the C++ standard the default is changed. Though I am not yet sure why this causes an issue (unless of course, its just that we end up with Folly's compilation of GFlags one way and ours another) ... looking into it.
