### ISSUE TITLE
Add a dynamic loader for plugins

### ISSUE THREAD

**Issue by sh00s** [facebookincubator/LogDevice#56]
Currently the only way to load plugins is to build them as a static library, export the `logdevice_plugin()` symbol and link them to the binary that uses the logdevice library. `StaticPluginLoader` then picks them up:
https://github.com/facebookincubator/LogDevice/blob/e6424a70735b589d0be1ed8a25f7a273a2198df3/logdevice/common/plugin/StaticPluginLoader.cpp#L13-L31

This is inconvenient, as this requires a rebuild of the binary every time something in the plugin changes. In addition to that, a dynamic plugin loader should be developed. It should pick up `.so` files from a certain folder, and then load all the plugins exported by those.

**Comment by MohamedBassem** [comment]
I landed a DynamicPluginLoader in ecef29fc5dcaf56396396a1a895f071f3641fa81.
