### ISSUE TITLE
build with issue:Unknown CMake command "thrift_generate".

### ISSUE THREAD

**Issue by louis-yang** [facebookincubator/LogDevice#61]
I encounter error when  I try to build logdevice:
OpenTracing includes: /home/hadoop/LogDevice/_build/external/opentracing/src/OpenTracing-build/include
CMake Error at admin/if/common/fb303/if/CMakeLists.txt:13 (thrift_generate):
  Unknown CMake command "thrift_generate".

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
DOUBLE_CONVERSION_INCLUDE_DIR (ADVANCED)

Any suggestion?

**Comment by louis-yang** [comment]
after run git submodule update --init --recursive,the "thrift_generate" issue is fixed.
still have problem with below:

-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   context
--   chrono
--   date_time
--   filesystem
--   program_options
--   regex
--   system
--   thread
--   python-py35
--   atomic
-- Boost Python Component python-py35 found
-- Found ZSTD library: /usr/lib64/libzstd.so
-- Found libevent: /usr/lib64/libevent.so
-- The C compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/local/bin/gcc
-- Check for working C compiler: /usr/local/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find DOUBLE_CONVERSION (missing: DOUBLE_CONVERSION_LIBRARY DOUBLE_CONVERSION_INCLUDE_DIR) 
-- Using third-party bundled double-conversion
-- Could NOT find LIBGLOG (missing: LIBGLOG_LIBRARY LIBGLOG_INCLUDE_DIR) 
-- Found LZ4: /usr/lib64/liblz4.so
-- Found SQLite: /usr/lib64/libsqlite3.so
-- Found Snappy: /usr/lib64/libsnappy.so
-- Found libiberty: /usr/lib64/libiberty.a
OpenTracing includes: /home/hadoop/LogDevice/_build/external/opentracing/src/OpenTracing-build/include
Thrift will create the Object file : admin-cpp2-obj
Thrift will create the Library file : admin-cpp2
-- Linking Python bindings with /usr/local/python35/lib/libpython3.5m.a
-- Python library will be installed to python3.5/site-packages
CMake Warning (dev) in ops/CMakeLists.txt:
  A logical block opening on the line

    /home/hadoop/LogDevice/logdevice/ops/CMakeLists.txt:10 (if)

  closes on the line

    /home/hadoop/LogDevice/logdevice/ops/CMakeLists.txt:13 (endif)

  with mis-matching arguments.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
DOUBLE_CONVERSION_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/hadoop/LogDevice/logdevice
   used as include directory in directory /home/hadoop/LogDevice/logdevice
   used as include directory in directory /home/hadoop/LogDevice/logdevice
   used as include directory in directory /home/hadoop/LogDevice/logdevice
   used as include directory in directory /home/hadoop/LogDevice/logdevice
   used as include directory in directory /home/hadoop/LogDevice/logdevice
   used as include directory in directory /home/hadoop/LogDevice/logdevice
   used as include directory in directory /home/hadoop/LogDevice/logdevice
   used as include directory in directory /home/hadoop/LogDevice/logdevice
   used as include directory in directory /home/hadoop/LogDevice/logdevice
   used as include directory in directory /home/hadoop/LogDevice/logdevice
   used as include directory in directory /home/hadoop/LogDevice/logdevice
   used as include directory in directory /home/hadoop/LogDevice/logdevice
   used as include directory in directory /home/hadoop/LogDevice/logdevice
   used as include directory in directory /home/hadoop/LogDevice/logdevice
   used as include directory in directory /home/hadoop/LogDevice/logdevice
   used as include directory in directory /home/hadoop/LogDevice/logdevice/external/gtest
   used as include directory in directory /home/hadoop/LogDevice/logdevice/external/gtest
   used as include directory in directory /home/hadoop/LogDevice/logdevice/external/gtest
   used as include directory in directory /home/hadoop/LogDevice/logdevice/external/gtest
   used as include directory in directory /home/hadoop/LogDevice/logdevice/external/gtest
   used as include directory in directory /home/hadoop/LogDevice/logdevice/external/gtest
   used as include directory in directory /home/hadoop/LogDevice/logdevice/external/gtest
   used as include directory in directory /home/hadoop/LogDevice/logdevice/external/gtest

**Comment by calebmarchent** [comment]
Hi @louis-yang, it looks like some of the prerequisite packages are not installed (e.g. double-conversion and glog? 
There are lists of required packages in https://github.com/facebookincubator/LogDevice/tree/master/logdevice/build_tools, please ensure these required packages are installed and re-run cmake.

I also note that you have libboost 1.67; which would suggest that you are trying to build with a distribution version newer than Ubuntu 18.04, for example Debian Buster or Ubuntu 18.10?
Please can you confirm the distribution and version you are compiling against?

**Comment by louis-yang** [comment]
ok，thanks very much ,this is very helpful.And I checkout list of required packages,if it with required version for each package,it must very helpful.actually I have to do upgrade some of these packages,when I am trying to build logdevice.
for my system is centos 6.7，I don't know if it have any problem with libboost 1.67? I just upgrade from older one.

**Comment by calebmarchent** [comment]
I think building natively under CentOS6.7 is going to be tricky, as it lacks a considerable number of packages or packages versions required for successful compilation. I would propose that to start with you consider building within a container, we a working Dockerfile for Ubuntu 18.04.

**Comment by louis-yang** [comment]
sound good，thanks for your advice

**Comment by calebmarchent** [comment]
Advice provided, no further action planned, closing.
