### ISSUE TITLE
ldshell `logs show` is broken in OSS build

### ISSUE THREAD

**Issue by MohamedBassem** [facebookincubator/LogDevice#62]
Steps to reproduce:

- Start a local cluster using `ld-dev-cluster` using the ubuntu docker image
- ldhsell into this cluster
- Run `logs show`
- It crashes with:
```
root@/dev/shm/tmp/logdevice/IntegrationTestUtils.510e-92fc-9dcd-57c2/logdevice.conf> logs show
Error running command: 'ascii' codec can't encode character '\u25bc' in position 5: ordinal not in range(128)
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nubia/internal/cmdbase.py", line 363, in run_interactive
    ret = fn(**args_dict)
  File "/usr/local/lib/python3.6/dist-packages/ldshell/autoload/commands/logsconfig.py", line 514, in show
    node, max_depth=max_depth, log_groups=True, show_version=True
  File "/usr/local/lib/python3.6/dist-packages/ldshell/autoload/commands/logsconfig.py", line 334, in _print_directory
    return _print_directory_helper(0, directory, max_depth, log_groups, show_version)
  File "/usr/local/lib/python3.6/dist-packages/ldshell/autoload/commands/logsconfig.py", line 309, in _print_directory_helper
    cprint(space_shift + "\u25BC " + directory.fully_qualified_name, "green")
  File "/usr/local/lib/python3.6/dist-packages/termcolor.py", line 124, in cprint
    print((colored(text, color, on_color, attrs)), **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode character '\u25bc' in position 5: ordinal not in range(128)
------------------------------------------------------------
```

**Comment by MohamedBassem** [comment]
Even easier, running this inside the container triggers the error.

```
python3 -c 'from termcolor import cprint; cprint("Hello\u25BC", "green")'
```

I tried it on my personal laptop outside the container and it worked correctly. I use the same `termcolor` version, but the main difference is that the python inside the container is `Python 3.6.7` while the one on my laptop is `Python 3.7.0`. So I assume maybe we want to install python 3.7 in the container instead?

**Comment by ylectric** [comment]
@MohamedBassem, unfortunately, Nubia and hence LDShell are not Python 3.7 compatible at the moment (see https://github.com/facebookincubator/python-nubia/issues/2). I hope @calebmarchent and/or myself will be able to address it soon(-ish).

**Comment by calebmarchent** [comment]
Logs Show is using hardcoded utf-8 charaters to render the tree; ▼ is "\u25BC". But by default the docker container shell is configured without UTF-8 support. 
One can work-around the issue by setting the locale in the terminal:

```
root@af2893e7f15f:/# export LANG=C.UTF-8
root@af2893e7f15f:/# ldshell -c /dev/shm/tmp/logdevice/IntegrationTestUtils.5714-ed1a-5e36-c72b/logdevice.conf
Logging to /tmp/ldshell-pcjjglrc
Logging Level: WARNING
root@/dev/shm/tmp/logdevice/IntegrationTestUtils.5714-ed1a-5e36-c72b/logdevice.conf> logs show
▼ /
  Version: 1
  Attributes:
  - extra-copies: 0    (Overridden)
  - synced-copies: 0    (Overridden)
  - max-writes-in-flight: 1000    (Overridden)
  - single-writer: False    (Overridden)
  - sequencer-affinity: None    (Overridden)
  - nodeset-size: None    (Overridden)
  - backlog: None    (Overridden)
  - delivery-latency: None    (Overridden)
  - scd-enabled: False    (Overridden)
  - local-scd-enabled: False    (Overridden)
  - write-token: None    (Overridden)
  - sticky-copysets: False    (Overridden)
```
Docker containers are intended to provide lean controlled environments for individual services to run in so the majority of the terminal things we are used to as developers are not present (e.g. an editor).

In terms of a solution: we could update the Docker container shell to have UTF-8 enabled. Or we could remove the UTF-8 characters from the ldshell UI, replacing "▼" with "V" and  "▶" with ">".

**Comment by calebmarchent** [comment]
Discussed further internally: the key features of ldshell include enhanced and hence intuitive presentation; use of UTF-8 will remain.
Next Action: Configure the Docker instance shells to include UTF-8.

**Comment by calebmarchent** [comment]
Fixed by: https://github.com/facebookincubator/LogDevice/pull/63
