### ISSUE TITLE
Sample standalone client app based on examples

### ISSUE THREAD

**Issue by gcameo** [facebookincubator/LogDevice#66]
I think the learning curve with LogDevice is too steep.. I have tried a few time but haven't managed to get off the fly very well so I am thinking if you could break the examples folder into some simple standalone projects that shows how to do a basic read and write but shows all the dependencies, we could use that as project templates to get going quicker...

Also, we need to list somewhere the external dependencies needed for a client. Is everything in the external folder required? or Just fizz and folly?

**Comment by calebmarchent** [comment]
Hi @gcameo many thanks for the feedback. We will be looking at simplifying the "Getting Started" process incrementally as we move forward.

All dependencies are either listed in the *.deps files, e.g. ubuntu.deps or are compiled as External Projects within the git project. (see CMake/build-*.)

**Comment by mzbeck** [comment]
Hi @gcameo 

there are a few standalone examples for reads and writes under /logdevice/examples.

They show how to use the client API, which is discussed here: https://logdevice.io/docs/API_Introduction.html

(from the bottom of that page)
Running the samples
To run the samples, follow the instructions in Running a local cluster to start a local cluster. Next, create a log range using ldshell logs create. Run the sample with --help to make it display a list of its options.

If you have more questions, please ask in the LogDevice Users group on Facebook.
