### ISSUE TITLE
Skip tests when building LogDevice

### ISSUE THREAD

**Issue by gcameo** [facebookincubator/LogDevice#68]
Is there a way I can skip testing when doing a LogDevice build. This is just to tryout examples so I really don't care much about test.. Is this possible?

**Comment by calebmarchent** [comment]
Hi @gcameo tests are only run on the `make test` target; so if you miss that target out of the steps, then tests should not be run. If you find otherwise, please do provide further information so that we can take a look?

**Comment by gcameo** [comment]
Thanks @calebmarchent . On the installation page, this is the make command
`make -j $(nproc)`
How do you exclude test in this command? Sorry, I am a bit new to c++ so don't know the tools that well.

**Comment by calebmarchent** [comment]
`make -j $(nproc)` does not include unit test steps.
the option `-j` configures the number of concurrent build jobs for make to run in parallel.
typically the number of cpu cores gives an indication of the power of the host performing the build, and so typically we use $(nproc) to get that size and pass it to the make command.

**Comment by gcameo** [comment]
Thanks. I think I will comment out the 
`add_subdirectory(test)`
in the CMakeLists.txt file in logdevice directory to see if that builds fine

**Comment by calebmarchent** [comment]
"I think I will comment out the  `add_subdirectory(test)`"

Please could you provide a snippet of the build failure you are seeing? The symptoms you describe suggest you might be using an old CMake version, for successful compilation we really need CMake 3.10 or later installed; which supports the discovery of GoogleTests.

**Comment by gcameo** [comment]
Ahhh. No I am not getting a build failure. I started the logdevice build about an hour ago and its still building.. Now on 86% so I am thinking of how I can improve that. especially If I don't care about tests..

because it builds all the external libraries and runs lots of tests - which take too long

**Comment by gcameo** [comment]
OK.. I will close this for now then
