### ISSUE TITLE
Build failed on target rocksdb-prefix

### ISSUE THREAD

**Issue by monicsh** [facebookincubator/LogDevice#84]
Below error occurred on building log device (running 'make -j $(nproc)' on Ubuntu 18.04.2 LTS (Bionic Beaver) Virtual Box Image.
 
[ 66%] Built target logdevice_server
make[2]: *** No rule to make target 'rocksdb-prefix/src/rocksdb-build/librocksdb.a', needed by 'bin/logdeviced'. Stop.
CMakeFiles/Makefile2:158: recipe for target 'CMakeFiles/logdeviced.dir/all' failed
make[1]: *** [CMakeFiles/logdeviced.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mzbeck** [comment]
@monicsh We know about this issue and a fix is coming from rocksdb. It should land June 7 or sometime this weekend.

**Comment by AhmedSoliman** [comment]
I think you have forgot to pull and update the submodules of the git repository. Have you been following our build guide?

**Comment by monicsh** [comment]
I have followed the build guidance for Ubuntu platform as per given. It was cloned with --recurse-submodules, so all submodules are pulled into the local directory.

**Comment by mzbeck** [comment]
@monicsh Just to confirm, did you try the build again yesterday? it was broken last week, but I was able to build from a clean system yesterday. The build is fixed now, it says failing in circleci but that's because of a couple of flaky tests.

**Comment by monicsh** [comment]
@mzbeck Yes, build is successful (on commit : b0e709a7bee6363820917d11507354d19456f811). Thanks for your help.
