### ISSUE TITLE
Ubuntu Docker Build failed 

### ISSUE THREAD

**Issue by monicsh** [facebookincubator/LogDevice#91]
Below issue is found while building ubuntu docker image:
`docker build -t logdevice-ubuntu -f docker/Dockerfile.ubuntu --target=builder .`  

Compilation terminated  while compiling `admin/CMakeFiles/logdevice_admin.dir/AdminAPIHandler.cpp.o` due to included file `common/fb303/cpp/FacebookBase2.h` not found.

![image](https://user-images.githubusercontent.com/7293474/60313848-73f04580-9915-11e9-967a-c4b3206aa7b8.png)

I instead found as `<workdir>/LogDevice/common/fb303/cpp/FacebookBase2.h`

**Comment by AhmedSoliman** [comment]
I've confirmed that this is broken, I will take a look at this next week. For now you can use the pre-built docker image that we offer
```
docker run -it --name mycluster facebookincubator/logdevice
```
